# Generated by Django 4.2.23 on 2025-09-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('mode', models.CharField(blank=True, choices=[('fulltime', 'تمام\u200cوقت'), ('parttime', 'پاره\u200cوقت'), ('contract', 'پروژه\u200cای'), ('remote', 'دورکاری')], max_length=20)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('project_type', models.CharField(choices=[('web', 'وب'), ('mobile', 'موبایل'), ('both', 'هر دو')], default='web', max_length=20)),
                ('scopes', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=60)),
                ('message', models.TextField()),
                ('nda', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
